const categories = [
  { name: "Public Infrastructure" },
  { name: "Sanitation & Waste Management" },
  { name: "Water Supply & Drainage" },
  { name: "Electricity & Power Supply" },
  { name: "Law & Order" },
  { name: "Health Services" },
  { name: "Environmental Issues" },
  { name: "Housing & Urban Development" },
  { name: "Education Services" },
  { name: "Transportation" },
  { name: "Corruption & Governance" },
  { name: "Civic Amenities" },
  { name: "Taxes & Utility Billing" },
  { name: "Employment & Labor" },
  { name: "Digital Services & E-Governance" },
  { name: "Licensing & Permits" },
  { name: "Consumer Rights" },
  { name: "Welfare & Social Services" },
];
